### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by LNQVAN** [aws-samples/aws-iot-edukit-tutorials#22]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by rashedtalukder** [comment]
Hi, what is your feature request? Can you please post some details following the questionnaire template above?

**Comment by rashedtalukder** [comment]
No response for 5 days with no feature request inputs. Closing.
